// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLmCxpn-IzvCJaOmR2qPWM9sTJW6NcKg8',
    appId: '1:123456789:web:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'flutter-mobail-app',
    authDomain: 'flutter-mobail-app.firebaseapp.com',
    storageBucket: 'flutter-mobail-app.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0ixuQkqw6mLz_TJyMuvxgoda-7EHYLpE',
    appId: '1:521943549759:android:f9dd4566211dc19485b58a',
    messagingSenderId: '521943549759',
    projectId: 'flutter-mobail-app',
    storageBucket: 'flutter-mobail-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLmCxpn-IzvCJaOmR2qPWM9sTJW6NcKg8',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'flutter-mobail-app',
    storageBucket: 'flutter-mobail-app.appspot.com',
    iosBundleId: 'com.example.palestinemartyrs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLmCxpn-IzvCJaOmR2qPWM9sTJW6NcKg8',
    appId: '1:123456789:macos:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'flutter-mobail-app',
    storageBucket: 'flutter-mobail-app.appspot.com',
    iosBundleId: 'com.example.palestinemartyrs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLmCxpn-IzvCJaOmR2qPWM9sTJW6NcKg8',
    appId: '1:123456789:windows:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'flutter-mobail-app',
    authDomain: 'flutter-mobail-app.firebaseapp.com',
    storageBucket: 'flutter-mobail-app.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );
}